In [1]:
import missing_methods as mm
import numpy as np
import hoggorm as ho

In [2]:
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9]])
Y = np.array([[2.4, 2.9],
              [0.6, 0.5],
              [2.1, 2.2]])

In [3]:
print(mm.rv(X, Y))
print(mm.rv_list([X, Y]))
print(ho.RVcoeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0)]))
print(mm.rv2(X, Y))
print(mm.rv2_list([X, Y]))
print(ho.RV2coeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0)]))

0.9209514798563275
[[1.         0.92095148]
 [0.92095148 1.        ]]
[[1.         0.92095148]
 [0.92095148 1.        ]]
0.8934727185169297
[[1.         0.89347272]
 [0.89347272 1.        ]]
[[1.         0.89347272]
 [0.89347272 1.        ]]


In [4]:
mm.pls(X, Y, ncomp=2)

{'scores': array([[ 0.82945384,  0.28751703],
        [-1.79021053, -0.0137231 ],
        [ 0.96075669, -0.27379393]]),
 'weights': array([[ 0.71961413,  0.69437419],
        [ 0.69437419, -0.71961413]]),
 'loadings_x': array([[ 0.68360919,  0.69437419],
        [ 0.73168788, -0.71961413]]),
 'loadings_y': array([[0.60926336, 0.67698308],
        [0.75250212, 1.42310723]]),
 'explained': array([4.81590083, 0.15781748]),
 'means_x': array([1.73333333, 2.        ]),
 'means_y': array([1.7       , 1.86666667]),
 'residual_x': array([[ 2.77555756e-17,  2.77555756e-17],
        [-3.81639165e-17, -3.81639165e-17],
        [ 2.77555756e-17,  0.00000000e+00]]),
 'residual_y': array([[-2.77555756e-17,  1.11022302e-16],
        [ 4.68375339e-17,  3.57353036e-16],
        [ 0.00000000e+00,  2.22044605e-16]])}

In [5]:
rng = np.random.default_rng(2026)
X = rng.standard_normal((120, 20))
Y = rng.standard_normal((120, 20)) + X
Z = rng.standard_normal((120, 20)) + X
Xnan = X.copy()
Ynan = Y.copy()
Znan = Z.copy()
Xnan[[0, 4, 7], 2] = np.nan
Ynan[[1, 3, 9], 4] = np.nan
Znan[[2, 5, 8], 6] = np.nan
print("RV without missing data:", mm.rv(X, Y))
print("RV with missing data:", mm.rv(Xnan, Ynan))
print("RV list without missing data:", mm.rv_list([X, Y, Z]))
print("RV list with missing data:", mm.rv_list([Xnan, Ynan, Znan]))
ho.RVcoeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0), Z - np.mean(Z, axis=0)])

RV without missing data: 0.559365400476794
RV with missing data: 0.5561979926224933
RV list without missing data: [[1.         0.5593654  0.56180147]
 [0.5593654  1.         0.34775426]
 [0.56180147 0.34775426 1.        ]]
RV list with missing data: [[1.         0.55619799 0.55863965]
 [0.55619799 1.         0.34487582]
 [0.55863965 0.34487582 1.        ]]


array([[1.        , 0.55936541, 0.56180148],
       [0.55936541, 1.        , 0.34775423],
       [0.56180148, 0.34775423, 1.        ]])

In [6]:
# Example with mm.pca
out1 = mm.pca(Xnan, ncomp=5)

# Hoggorm example
hopca = ho.nipalsPCA(X, numComp=5)

In [7]:
out1["scores"][:5, :5]

array([[-0.31338408,  0.79539085, -0.55911502,  0.4657077 , -0.58839135],
       [-1.83080892, -0.62772433, -0.02282385,  0.98900599, -1.08030779],
       [ 2.29825572,  1.5014746 , -0.0565446 , -0.98056755,  1.06346394],
       [-2.25427008, -1.52869558,  2.4787884 , -0.95347857, -0.06331295],
       [ 0.37911283,  2.84274654,  1.46568537, -0.7410889 ,  0.5972406 ]])

In [8]:
hopca.X_scores()[:5, :5]

array([[-0.05661093,  0.73779957,  0.36182842, -0.22318321, -0.76213281],
       [-1.83450677, -0.61571983,  0.02330123,  0.85685066, -1.23186402],
       [ 2.31045785,  1.4936774 , -0.07617076, -0.95756508,  1.11150737],
       [-2.28504626, -1.43540251,  2.45486629, -0.97222205,  0.16098958],
       [ 0.36549845,  2.88370128,  1.29471403, -0.42134402,  0.81379832]])

In [9]:
#pip install -e ..

In [10]:
# Example with mm.mfa
mfa_blocks = [Xnan[:, :10], Ynan[:, :10], Znan[:, :10]]
out_mfa = mm.mfa(mfa_blocks, ncomp=3)
print("Explained variance:", np.round(out_mfa["explained_variance"][:3], 3))
print("Block corrload shapes:", [b.shape for b in out_mfa["block_correlation_loadings"]])
out_mfa["scores"][:3, :3]

Explained variance: [0.12  0.108 0.1  ]
Block corrload shapes: [(10, 3), (10, 3), (10, 3)]


array([[-0.03762572, -0.02786412,  0.13283376],
       [-0.11160903,  0.09092924, -0.06070289],
       [ 0.166431  , -0.18519048, -0.05906784]])

In [11]:
out_mfa

{'scores': array([[-3.76257188e-02, -2.78641193e-02,  1.32833762e-01],
        [-1.11609034e-01,  9.09292448e-02, -6.07028851e-02],
        [ 1.66431002e-01, -1.85190484e-01, -5.90678366e-02],
        [-2.07128983e-01, -2.04396967e-02,  8.17301167e-02],
        [ 6.35348978e-02, -5.81895539e-04,  9.09090226e-02],
        [-1.87311161e-01, -1.26984558e-01, -1.46580952e-01],
        [-7.41775086e-02,  5.49583703e-02,  7.44926255e-02],
        [ 6.06788628e-05,  1.57379632e-02,  2.67301044e-02],
        [ 1.17642134e-01,  3.01255220e-01, -2.02052605e-01],
        [-5.39945680e-02,  4.14095351e-01, -1.01570110e-01],
        [-7.63461195e-02, -6.84723233e-02, -8.97396848e-02],
        [-1.59795636e-01, -7.19688854e-03,  7.33320815e-03],
        [ 1.91258710e-01,  9.48593460e-02, -1.03538969e-01],
        [-1.17499183e-02, -2.31824961e-01,  1.78095626e-01],
        [ 1.03716887e-01,  1.38068517e-01, -8.16675586e-02],
        [-1.12368862e-02,  2.09354502e-04, -1.28846331e-01],
        [-8.34

In [14]:
print(mm.normalize(Xnan))
print(mm.standardize(Xnan)) 

[[-0.06197069  0.02220627         nan ...  0.05510338 -0.01342836
  -0.12610917]
 [-0.03729221  0.06061037 -0.02095195 ... -0.04596992  0.05212919
   0.08044244]
 [ 0.01597239 -0.05796722 -0.07448881 ...  0.02852658  0.1325598
  -0.05097709]
 ...
 [ 0.13424084  0.08029091 -0.02014935 ... -0.0594988  -0.225686
  -0.10919528]
 [-0.02656747  0.06315244  0.01561733 ... -0.03279322 -0.09371536
  -0.13632455]
 [ 0.0221706  -0.12191602 -0.01350561 ... -0.07262405  0.11405017
  -0.04527993]]
[[-0.83224111  0.31547118         nan ...  0.66392837 -0.07991677
  -1.30200918]
 [-0.56004494  0.73552195 -0.14375162 ... -0.4407634   0.63684369
   0.95808303]
 [ 0.02744755 -0.56143864 -0.72234589 ...  0.37345435  1.51621568
  -0.47991232]
 ...
 [ 1.33191275  0.95078089 -0.13507759 ... -0.58862874 -2.40059333
  -1.11693699]
 [-0.44175424  0.76332624  0.25146726 ... -0.29674724 -0.95771873
  -1.41378608]
 [ 0.09581195 -1.26088844 -0.063276   ... -0.7320827   1.31384434
  -0.41757393]]
