In [2]:
import missing_methods as mm
import numpy as np
import hoggorm as ho

In [3]:
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9]])
Y = np.array([[2.4, 2.9],
              [0.6, 0.5],
              [2.1, 2.2]])

In [4]:
print(mm.rv(X, Y))
print(mm.rv_list([X, Y]))
print(ho.RVcoeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0)]))
print(mm.rv2(X, Y))
print(mm.rv2_list([X, Y]))
print(ho.RV2coeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0)]))

0.9209514798563275
[[1.         0.92095148]
 [0.92095148 1.        ]]
[[1.         0.92095148]
 [0.92095148 1.        ]]
0.8934727185169297
[[1.         0.89347272]
 [0.89347272 1.        ]]
[[1.         0.89347272]
 [0.89347272 1.        ]]


In [ ]:
mm.pls(X, Y, ncomp=2)

In [ ]:
rng = np.random.default_rng(2026)
X = rng.standard_normal((120, 20))
Y = rng.standard_normal((120, 20))
Xnan = X.copy()
Ynan = Y.copy()
Xnan[[0, 4, 7], 2] = np.nan
Ynan[[1, 3, 9], 4] = np.nan
print("RV without missing data:", mm.rv(X, Y))
print("RV with missing data:", mm.rv(Xnan, Ynan))
ho.RVcoeff([X - np.mean(X, axis=0), Y - np.mean(Y, axis=0)])

In [ ]:
# Example with mm.pca
out1 = mm.pca(Xnan, ncomp=5)

# Hoggorm example
hopca = ho.nipalsPCA(X, numComp=5)

In [ ]:
out1["scores"][:5, :5]

In [ ]:
hopca.X_scores()[:5, :5]